name: spotify_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  go_router: ^6.0.9
  webview_flutter: ^2.0.0
  get_it: ^7.6.0
  flutter_secure_storage: ^8.0.0
  bloc: ^8.1.3
  audioplayers: ^0.20.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.0
  flutter_appauth: ^4.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
